### ISSUE TITLE
Duplicate Firefox string on /welcome/6/ modal title

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8875]
## Description

The word Firefox is called out twice in the modal on /welcome page 6. Should the first instance be a logo instead?

![image](https://user-images.githubusercontent.com/400117/80983315-57217a00-8e24-11ea-8f27-cbdf917a0f5c.png)

### Steps to reproduce

1. Using Firefox (set as the default browser), visit https://www.mozilla.org/en-US/firefox/welcome/6/
2. Click "Get the Firefox App"

### Expected result

Should it look similar to this (with "Firefox" replaced by a logo)?

![image](https://user-images.githubusercontent.com/400117/80983600-a1a2f680-8e24-11ea-9116-6bbde0e04ba4.png)

### Actual result

Firefox is repeated twice

### Environment
Firefox Nightly

**Comment by aannaassalam** [comment]
May I get a link to that Firefix logo and another link to css and html file to make changes in...

**Comment by aannaassalam** [comment]
I think your bug is solved as in [this link](https://www.mozilla.org/en-US/firefox/mobile/) there is a Logo on top of the Get Firefox for mobile and its looking pretty awesome

**Comment by ForgottenProgramme** [comment]
> I think your bug is solved as in this link there is a Logo on top of the Get Firefox for mobile and its looking pretty awesome

Yes, @alexgibson . 
I think the bug is already fixed. 
When I open the link you attached I see this; 

![mozilla](https://user-images.githubusercontent.com/65779580/82867900-4955a500-9f49-11ea-8702-39c15b68de7f.png)

The logo is there.

**Comment by alexgibson** [comment]
Following the steps to reproduce outlined in the issue description, I'm still able to reproduce this issue, so it's not fixed.

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?
