### ISSUE TITLE
Requesting update to Internet Health Report newsletter title and description on email preference center

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/bedrock#9401]
Opening issue per discussion with @pmac

Current copy for newsletter.
**Title:** Internet Health Report
**Description:** Keep up with our annual compilation of research and stories on the issues of privacy & security, openness, digital inclusion, decentralization, and web literacy. 

Updated copy for newsletter.
**Title:** Insights
**Description:** Mozilla publishes articles and deep dives on issues around internet health and trustworthy AI, including our annual Internet Health Report.

**Comment by pmac** [comment]
I've looked in our translations and these strings are translated into a few languages. Is this newsletter English only by chance? We'll need to decide if having these strings translated on the page is important or not. The page is still using the old l10n system so we'd also likely need to convert it to the new Fluent system if we want to have new strings translated.

@alexgibson thoughts?

**Comment by alexgibson** [comment]
I'm not 100% of the status of the strings for the preferences page, or how many languages it supports, but we need to migrate these pages to Fluent eventually either way. If this is a good means to helping prioritize that work, then I'd say we should do it. I'll add this card to the project board backlog.

**Comment by stephaniemcv** [comment]
Hey @alexgibson just checking in if you have an eta on when this pages will be migrated to Fluent?

**Comment by alexgibson** [comment]
@stephaniemcv I can try and get to this soon, just as soon as the unfck campaign work is wrapped up. Thanks for your patience

**Comment by stephaniemcv** [comment]
No worries at all. I just want to be able to communicate back accurately on the status. Thank you for the update!

**Comment by stephaniemcv** [comment]
Hey ya'll,
Wanted to check-in on the status on this. Based on the tickets it looks like this was closed, however the text on preference center hasn't been updated.

**Comment by pmac** [comment]
D'oh! I thought this was fixed when that last PR merged. I'll take another look and see what's up.

**Comment by pmac** [comment]
The issue seems to be that the newsletter's slug in basket was actually `internet-health-report-group` and in the bedrock code it was looking for `internet-health-report`. So I've updated it in basket, so the site should update shortly. 

Also, this is setup as a group that subscribes people to both `internet-health-report` and `mozilla-foundation`. Is that still what you want?

**Comment by stephaniemcv** [comment]
Ah that makes sense. And yes, the setup that subscribes people to both is correct. At this time the Insights group still can't support enough content for a full year.

**Comment by pmac** [comment]
@stephaniemcv great. Can you post links to any forms you know of that are subscribing people to this group? I'd like to double check that we're all using the right name for the subscription group.

**Comment by pmac** [comment]
Looks right to me now.

![Screen Shot 2021-01-25 at 10 01 22](https://user-images.githubusercontent.com/19176817/105723056-553ca100-5ef4-11eb-9cba-7e8eb11360d3.png)

**Comment by stephaniemcv** [comment]
Great, thank you!

**Comment by alexgibson** [comment]
Looks like this was fixed
